[package]
name = "ft6x06"
version = "0.1.0"
edition = "2021"
authors = ["Shantanu Gaikwad"]
categories = ["embedded", "no-std"]
description = "A platform agnostic driver for the FT6x06 type touch screen driver used on STM32F413 board."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
